#!/bin/bash
source option-l.sh
source option-lsort.sh
source option-d.sh
source option-c.sh
source option-h.sh

RED='\033[0;31m'
NC='\033[0m' # No Color
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
echo -e "${BLUE}"
echo "
	 █     █░ ██▓  ██████  ▄████▄   ██▀███   ██▓ ██▓███  ▄▄▄█████▓
	▓█░ █ ░█░▓██▒▒██    ▒ ▒██▀ ▀█  ▓██ ▒ ██▒▓██▒▓██░  ██▒▓  ██▒ ▓▒
	▒█░ █ ░█ ▒██▒░ ▓██▄   ▒▓█    ▄ ▓██ ░▄█ ▒▒██▒▓██░ ██▓▒▒ ▓██░ ▒░
	░█░ █ ░█ ░██░  ▒   ██▒▒▓▓▄ ▄██▒▒██▀▀█▄  ░██░▒██▄█▓▒ ▒░ ▓██▓ ░
	░░██▒██▓ ░██░▒██████▒▒▒ ▓███▀ ░░██▓ ▒██▒░██░▒██▒ ░  ░  ▒██▒ ░
	░ ▓░▒ ▒  ░▓  ▒ ▒▓▒ ▒ ░░ ░▒ ▒  ░░ ▒▓ ░▒▓░░▓  ▒▓▒░ ░  ░  ▒ ░░
	  ▒ ░ ░   ▒ ░░ ░▒  ░ ░  ░  ▒     ░▒ ░ ▒░ ▒ ░░▒ ░         ░
	  ░   ░   ▒ ░░  ░  ░  ░          ░░   ░  ▒ ░░░         ░
	    ░     ░        ░  ░ ░         ░      ░
	                    ░
"
echo -e "\n \t \t \t ${RED}"
echo -e "\t \t[------------------------------------------------------------]\n"
echo -e "\t \t[                Welcome to WiScript Tool                    ]\n"
echo -e "\t \t[------------------------------------------------------------]\n ${NC}"
echo -e "\n"

if [[ $# -eq 0 ]]; then
echo -e "${YELLOW} 1: ${NC} List available Acces Points."
echo -e "${YELLOW} 2: ${NC} List available Acces Points ordered by signal intensity."
echo -e "${YELLOW} 3: ${NC} Diactivate NetworkManager service."
echo -e "${YELLOW} 4: ${NC} Manually configur Acces point's acces."
echo -e "${YELLOW} 5: ${NC} Check Update."
echo -e "${YELLOW} 6: ${NC} Help."
echo -e "${YELLOW} 7: ${NC} Exit."
fi
while true ; do
	#statements

if [[ $# -eq 0 ]]; then
echo -e "\n ${BLUE}"
read -p "W15cr1p7 ➡️ " Choix
echo -e "\n ${NC}"
else
Choix=$1
fi

case "$Choix" in

	"-l")
		option-l
		exit
		;;
	"-lsort")
		option-lsort
		exit
		;;
	"-d")
		option-d
		exit
		;;
	"-c")
		option-c
		exit
		;;
	"-help" | "-h")
		Help
		exit
		;;
	"-version" | "-v")
	 		version
	 		exit
	 		;;
	"1")
		option-l
		;;
	"2")
		option-lsort
		;;
	"3")
		option-d
		;;
	"4")
		option-c
		;;
	"5")
		update
		;;
	"6")
			Help
			;;
	"7"| "exit")
	 echo -e "
		[++] Shutting down ... Goodbye. ( ^_^)／
	   "
		echo -e "\n \t \t   ${YELLOW}Thank you for using WiScript Tool ${RED}<3"
		exit
		;;
		*)
		echo "choix inconnus ! "
		exit
	  ;;

esac
done
