#!/bin/bash
source option-l.sh
source option-lsort.sh
source option-d.sh
source option-c.sh
source option-h.sh

RED='\033[0;31m'
NC='\033[0m' # No Color
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
echo -e "${BLUE}"
echo "
	 █     █░ ██▓  ██████  ▄████▄   ██▀███   ██▓ ██▓███  ▄▄▄█████▓
	▓█░ █ ░█░▓██▒▒██    ▒ ▒██▀ ▀█  ▓██ ▒ ██▒▓██▒▓██░  ██▒▓  ██▒ ▓▒
	▒█░ █ ░█ ▒██▒░ ▓██▄   ▒▓█    ▄ ▓██ ░▄█ ▒▒██▒▓██░ ██▓▒▒ ▓██░ ▒░
	░█░ █ ░█ ░██░  ▒   ██▒▒▓▓▄ ▄██▒▒██▀▀█▄  ░██░▒██▄█▓▒ ▒░ ▓██▓ ░
	░░██▒██▓ ░██░▒██████▒▒▒ ▓███▀ ░░██▓ ▒██▒░██░▒██▒ ░  ░  ▒██▒ ░
	░ ▓░▒ ▒  ░▓  ▒ ▒▓▒ ▒ ░░ ░▒ ▒  ░░ ▒▓ ░▒▓░░▓  ▒▓▒░ ░  ░  ▒ ░░
	  ▒ ░ ░   ▒ ░░ ░▒  ░ ░  ░  ▒     ░▒ ░ ▒░ ▒ ░░▒ ░         ░
	  ░   ░   ▒ ░░  ░  ░  ░          ░░   ░  ▒ ░░░         ░
	    ░     ░        ░  ░ ░         ░      ░
	                    ░
"
echo -e "\n \t \t \t ${RED}"
echo -e "\t \t[------------------------------------------------------------]\n"
echo -e "\t \t[                Welcome to WiScript Tool                    ]\n"
echo -e "\t \t[------------------------------------------------------------]\n ${NC}"
echo -e "\n"

if [[ $# -eq 0 ]]; then
echo -e "${YELLOW} 1: ${NC} Lister les différents points d'acces wifi."
echo -e "${YELLOW} 2: ${NC} Lister les points d'acces wifi par ordre decroissant d'intensite de signal."
echo -e "${YELLOW} 3: ${NC} Disactiver le service NetworkManager."
echo -e "${YELLOW} 4: ${NC} Configurer manuellement l'accès a un point d'acces."
echo -e "${YELLOW} 5: ${NC} Help."
echo -e "${YELLOW} 6: ${NC} Exit."
fi
while [[ true ]]; do
	#statements

if [[ $# -eq 0 ]]; then
echo -e "\n ${BLUE}"
read -p "W15cr1p7 ➡️ " Choix
echo -e "\n ${NC}"
else
Choix=$1
fi

case "$Choix" in

	"-l")
		option-l
		exit
		;;
	"-lsort")
		option-lsort
		exit
		;;
	"-d")
		option-d
		exit
		;;
	"-c")
		option-c
		exit
		;;
	"-help" | "-h")
		Help
		exit
		;;
	"1")
		option-l
		;;
	"2")
		option-lsort
		;;
	"3")
		option-d
		;;
	"4")
		option-c
		;;
	"5")
		Help
		;;
	"6"| "exit")
	 echo -e "
		[++] Shutting down ... Goodbye. ( ^_^)／
	   "
		echo -e "\n \t \t   ${YELLOW}Thank you for using WiScript Tool ${RED}<3"
		exit
	  ;;

esac
done
