#!/bin/bash
source option-l.sh
source option-lsort.sh
source option-d.sh
source option-c.sh
source option-h.sh

RED='\033[0;31m'
NC='\033[0m' # No Color
YELLOW='\033[1;33m'
if [[ $# -eq 0 ]]; then
echo -e "\n \t \t \t ${RED}Welcome to WiScript Tool ${NC} \n "
echo -e "${YELLOW} 1: ${NC}Lister les différents points d'acces wifi."
echo -e "${YELLOW} 2: ${NC} Lister les points d'acces wifi par ordre decroissant d'intensite de signal."
echo -e "${YELLOW} 3: ${NC} Disactiver le service NetworkManager."
echo -e "${YELLOW} 4: ${NC} Configurer manuellement l'accès a un point d'acces."
echo -e "${YELLOW} 5: ${NC} Help."
echo -e "\n"
read Choix

else
Choix=$1
fi

case "$Choix" in

	"-l" | "1")
		option-l
		;;
	"-lsort" | "2")
		option-lsort
		;;
	"-d" | "3")
		option-d
		;;
	"-c" | "4")
		option-c
		;;
	"-h" | "5" | "-help")
		Help
		;;

esac
	 echo -e "\n \t \t   ${YELLOW}Thank you for using WiScript Tool ${RED}<3"
